### ISSUE TITLE
Upgrade AWS SDK 2 -> 3

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#108]
As discovered in #90 , upgrading the AWS SDK necessitates two bits of work:

1. Fix the errors in our code to address the SDK's breaking changes.
1. Pull in only the SDK modules that we need (now that v3 of the SDK is modular).

**Comment by clintoncwolfe** [comment]
Also note that we need to add explicit major version pinning (~> 1, for example) to the Gemfile.

**Comment by chris-redekop** [comment]
@clintoncwolfe , this is marked in review, but I don't see a review in-progress.  Would you please update?
