### ISSUE TITLE
Avoid using resource parameters for internal use

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/inspec-aws#110]
A resource parameter is an argument to the resource constructor.  

It looks like this to a control author:
```
describe aws_iam_user('bob') do
                     # ^^^  a 'resource parameter'
   ...
end
```

To a resource author, these parameters are passed as arguments to the resource constructor:
```
  # From aws_iam_user
  def initialize(
    opts,
    aws_user_provider = AwsIam::UserProvider.new,
    aws_user_details_provider_ini = AwsIam::UserDetailsProviderInitializer.new,
    access_key_factory = AwsIamAccessKeyFactory.new
  )
```

Here, the last three arguments would seem to be things that can be provided by factory classes.  Is there a strong need to parameterize them in this location?  If so, perhaps we could wrap that in a standardized runtime context object?

My motivation here is to keep our resource constructor interfaces clean and consistent, since they are user-exposed.

**Comment by chris-redekop** [comment]
Thanks for tidying up, Clinton!

The last three arguments are used as cheap DI for our unit tests, so we can mock those collaborators during unit testing.

Normally, I would add a protected overloaded constructor for this injection, which control authors don't see but that we can use.  Is there a good way to do something like this, or an alternative in InSpec/Ruby?

**Comment by clintoncwolfe** [comment]
Thanks - reading the unit tests for aws_iam_access_key has been very educational.  I see where it's being used for DI now.   There are a lot of ways that you can get a similar effect in Ruby, on a spectrum of ugliness :)

I'm thinking of two factors that push me toward wanting to avoid passing DI params to constructors:
 1. As mentioned above, the constructor is very public, not just to developers.  The constructors I see in inspec-aws follow an unusual (for Ruby) pattern - an explicit hash (which might in fact be a scalar), then optional DI params with default values.  Ruby more often uses implicit hashes, or named parameters (which looks the same to the caller).  If we used named parameters, you could still pass DI params, and even have defaults, without forcing explicit hash syntax on the caller.  I can give some examples if you like; it comes down to "why do I suddenly have to type curly brackets?"

 2.  The ultimate fate of inspec-aws is likely to be merged with core InSpec, or at least be maintained by the same teams.  Core InSpec does not use DI params for testing - instead tending to rely heavily on mocking.  

I'm working on #64 which involves a plural `aws_iam_access_keys` resource.  I'll use a pluggable provider class to either talk to AWS or a mocked provider.  For this, I'll use an alternate approach to dependency injection via constructor args - a factory method on an abstract class.

I suggest that we have a look at how it works on `aws_iam_access_keys`, and then decide how we like it.  

@chris-redekop , I've given a lot of design-level feedback over the last few days, and I just want to reiterate how grateful we are for all of your contributions.  I'm finally able to focus on inspec-aws full time, especially on issues of completeness and ease of integration into core inspec - that's why I'm calling out some potential rough spots.  I believe in "Strong opinions weakly held" - I'll look for reasons we should do something in a different way, make an argument, and if we need to go in the original direction, I have no problem with that.  Every software project is a work in progress, and there are no perfect answers; and my ideas are no more perfect than anyone else's.  I'm just looking for exploration and consensus around approaches.

Anyway, it's been a pleasure working with you so far, and I look forward to more in the future.  I just wanted to make sure that my recent "wave of commentary" doesn't feel critical.

**Comment by clintoncwolfe** [comment]
Here's the WIP branch for `aws_iam_access_keys` if you'd like to have a look.  I have the "DI via factory method" bit in place.  https://github.com/chef/inspec-aws/compare/cw/add-access-keys-plural-resource

**Comment by chris-redekop** [comment]
Thanks, Clinton, for being so tactful here.  :-)  Factory methods work well and I'm A-OK with using them instead of constructor injection.

For factory methods, in the case of `aws_iam_user`, you might consider the alternative of having three basic factory methods that can be overridden during testing:

```
  # From aws_iam_user
  def initialize(opts) 
    aws_user_provider = create_aws_user_provider() # we can override this during unit tests
  # ...
    @aws_user_details_provider = create_aws_user_details_provider(user)
```

Both are cheap and terse--they don't distract from the main class with test-enabling designs.  They also don't make any assumptions about dependency constructors.

Contrast this with AccessKeyProvider, which is a bit heavier and--I _think_--assumes no-arg constructors.

**Comment by clintoncwolfe** [comment]
After some discussion internally - especially motivated by wanting to be consistent with inspec-core - it looks like we're going to take on a brief re-factor of the innards of aws_iam_user and aws_iam_users, looking to remove DI constructor arguments and rework the unit tests to be more extensible (needed by #113 , for example).  Thanks again for all your work on this!
