### ISSUE TITLE
RFC: Avoid plural resources

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/inspec-aws#111]
Do we need to have both`aws_iam_user` and `aws_iam_users`  (which I call a "plural resource")?

This puts us in a position of having to duplicate (or make awkward, two-target refactorings) functionality.  This problem will get much worse - for every AWS resource, why wouldn't we need to have both a singular and a plural version of each resource?

Would it be possible to have only a singular-named resource, which implements FilterTable and thus may be used either way?

```
# Just bob
describe aws_iam_user('bob') ... end

# All users 
describe aws_iam_user ... end

# Fetch all users, then filter locally
describe aws_iam_user.where(name: 'bob') ... end

# Fetch only matching users 
describe aws_iam_user(has_profile: 'FabulousProfile') ... end
```

How do we handle properties and predicates when we have a list return?

**Comment by chris-redekop** [comment]
I'm happy to defer on this one.  I'll offer two perspectives:

1. I understood user/users to be an InSpec convention and brought them over.
1. As a new InSpec user, I found it natural to reason differently about users and a single user, and to identify this different reasoning with different resource names.

**Comment by clintoncwolfe** [comment]
On 1, it's an inconsistent convention in code InSpec, and has been a source of some regret.  As we're (eventually) adding a large number of resources in inspec-aws and similar extensions, we're just making sure it's a conscious decision.  

On 2, yeah, I share that concern.  Does it read well to have a singular noun fetch multiple objects?  (Could we address that with aliasing - `aws_iam_user` and `aws_iam_users` could in fact be the same implementation with different DSL exposure?).

Would this require changes to FilterTable?

What would it mean to access a property of a list result?

I'm very interested in thoughts, and examples of control code that "feels good" or "feels bad".

**Comment by clintoncwolfe** [comment]
Moving this over to inspec-core https://github.com/chef/inspec/issues/2277
