### ISSUE TITLE
The aws_iam_user resource doesn't appear to define "exists?"

### ISSUE THREAD

**Issue by ChefRycar** [chef/inspec-aws#114]
Per topic, this is causing the standard `it { should exist }` example to fail, even if other more specific matchers seem to be working without issue. 

Looks like this should be an easy fix in `libraries/aws_iam_user.rb`. Will take a crack at it!

**Comment by clintoncwolfe** [comment]
Thanks for the report!

Please feel free to reach out if you need any help!
