### ISSUE TITLE
Integration tests randomly fail due to eventual consistency

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/inspec-aws#122]
Portions of the integration tests (which talk to real AWS accounts) sometimes fail because we create  the resources, then immediately start testing for its existence.  

Once example is creating an SNS topic with an SQS subscription, which fails immediately, but succeeds if the AWS infra is left up and `rake test:run_integration_tests` a few minutes later.

Workarounds:

- Add a `sleep` after the terraform run.  There is no correct answer for the length of the sleep.
- Run the integration tests twice, and make it easier to run them with a previously setup infrastructure.

**Comment by aaronlippold** [comment]
So Yarick and I ran into this type of an issue with Terraform when we were building out the s3 bucket and then adding objects to the bucket. We solved it by using the terraform `depends_on` capability.
```
resource "aws_s3_bucket_object" "public-read" {
  bucket = "${var.aws_ssh_key_name}-aws_demo_bucket"
  acl    = "public-read"
  key    = "public-pic-read.jpg"
  source = "./data/public-pic.jpg"
  etag   = "${md5(file("./data/public-pic.jpg"))}"

  depends_on = ["aws_s3_bucket.aws_demo_bucket"]
}
```
Which solved the issue on the create side allowing terraform and AWS to be nice to each other and ensured the tests would be accurate. It does add a bit of time to the build process ( 10 seconds or so ) but keeps things smooth.
