### ISSUE TITLE
aws_ec2_security_group does not report the inspected security group name or id

### ISSUE THREAD

**Issue by aaronlippold** [chef/inspec-aws#143]
When you execute a control that uses the `aws_ec2_security_group` resource it should report the name of the security group in all formatters.

```
 ✔  aws_security_group: EC2 Security Group should exist
     ✔  EC2 Security Group should exist
```
should be something like:
```
 ✔  aws_security_group: EC2 Security Group should exist
     ✔  EC2 Security Group `sg-a12345` should exist
```

**Comment by clintoncwolfe** [comment]
This is a great thing to call out, and should be straighforward to add to the `to_s` method in `libraries/aws_ec2_security_group`.  If someone wants to make their first contribution, this would be a great chance!
