### ISSUE TITLE
Add resources for Config

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/inspec-aws#147]
There are a couple of resources needed to describe an AWS Config setup, including the delivery channel and configuration recorder.

For configuration recorder, singular resource, no properties, matchers: `be_enabled`, `be_recording_all_regional_changes`, `be_recording_all_global_changes`.

For delivery channel, singular resource, properties `s3_bucket`, `sns_topic`; matchers `be_enabled`.

Refs https://github.com/chef/inspec/issues/2233

**Comment by rx294** [comment]
Hello Clinton, please let me know are you still working on these resources...if not, I would like to hack at it if you don't mind...

**Comment by clintoncwolfe** [comment]
@rx294 I'm not actively working on it, no.  There is a very outdated branch, which basically just contains partial docs files and API notes, at cw/add-config.  We'd need 2 resources to cover CIS, I think.
