### ISSUE TITLE
Integration tests fail due to floating terraform aws plugin version

### ISSUE THREAD

**Issue by samcornwell** [chef/inspec-aws#148]
Running the integration tests on a freshly cloned repo with terraform 0.10.0 gives this result:

```
Initializing provider plugins...
- Downloading plugin for provider "aws"...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.6"
```
*snip*

```
You're now on a new, empty workspace. Workspaces isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
cd /Users/sam/projects/devsecops/inspec-aws/test/integration/default/build/ && AWS_PROFILE=inspec-aws-test-default terraform plan
Error asking for user input: 1 error(s) occurred:

* provider.aws: dial unix /var/folders/vj/_krnh7zj7l3d46z485bml_j00000gp/T/plugin261050608|netrpc: connect: no such file or directory
Integration testing has failed for the default account
----> Cleanup
cd /Users/sam/projects/devsecops/inspec-aws/test/integration/default/build/ && AWS_PROFILE=inspec-aws-test-default terraform destroy -force
Error asking for user input: 1 error(s) occurred:

* provider.aws: dial unix /var/folders/vj/_krnh7zj7l3d46z485bml_j00000gp/T/plugin005393920|netrpc: connect: no such file or directory
```

I had to step down the version of the aws provder in the aws.tf file until the tests were able to run successfully to completion.

```
provider "aws" {
  version = "= 1.1"
}
```

I was previously able to get things basically working by simply changing to the aws.tf file to use terraform 0.11.1, and was then able to use newest version of the aws provider (1.6).  Note that if you had previously installed aws provider 1.1, and you are using terraform 0.10.0, you don't need to hack the aws.tf file because terraform won't upgrade the provider unless it thinks it needs to.

**Comment by clintoncwolfe** [comment]
Thanks for the report!  I agree that we should version-pin the aws plugin.

I'm wondering what it's trying to prompt you for:
```
Error asking for user input: 1 error(s) occurred:
```

Do we need to document exposing another env var (perhaps `AWS_REGION`)?

**Comment by aaronlippold** [comment]
Yes AWS_REGION is one that needs to be exposed. @harkershark is working on pushing a set of small Pos which capture these small updates so we can easily merge them into mainline

**Comment by samcornwell** [comment]
Yeah, I guess it may have been asking for the region, not sure.

**Comment by clintoncwolfe** [comment]
Thanks for the fix!
