### ISSUE TITLE
log group not getting destroyed when running cleanup

### ISSUE THREAD

**Issue by dromazmj** [chef/inspec-aws#158]
* aws_cloudwatch_log_group.lmf_lg_1: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
	status code: 400, request id: 42c8562b-ea53-11e7-8c91-1b9599c30cf9:  The CloudWatch Log Group 'test_lmf_lg_1' already exists.
* aws_cloudwatch_log_group.lmf_lg_2: 1 error(s) occurred:

* aws_cloudwatch_log_group.lmf_lg_2: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
	status code: 400, request id: 42c325e3-ea53-11e7-bd6a-6feabf9a7ece:  The CloudWatch Log Group 'test_lmf_lg_2' already exists.
* aws_iam_instance_profile.profile_for_ec2_with_role: 1 error(s) occurred:

**Comment by clintoncwolfe** [comment]
Hi Matt, 
  It sounds like you had an interrupted or failed terraform run, leaving some resources orphaned (existing but untracked by TF state).  There are several ways that can happen; one would be using non-unique workspace names; if one of your colleagues on the same account used the same workspace name, you could have all sorts of problems.  [Here](https://github.com/chef/inspec-aws/blob/master/test/integration/default/build/cloudwatch.tf#L30) you can see where we prefix the log group with the workspace name; I can see you're using the word `test` above.

  To fix, I suggest you login to your AWS console and manually delete any offending resources.  Then, next time you run the integration tests, use a unique name for your environment when prompted (perhaps dromazmj-01).

Thanks!

**Comment by dromazmj** [comment]
Hi Clinton,
Thanks for the info.  I just wanted to make sure that this wasn't a problem with a cleanup.  So I'm glad it was just an interrupt issue.

Thanks!
