### ISSUE TITLE
VPC Subnet Resource

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/inspec-aws#169]
Skeletal singular and plural resources for VPC subnets.

Needed for general purpose resources.

Refs https://github.com/chef/inspec/issues/2233

**Comment by clintoncwolfe** [comment]
#172 gave the singular resource

**Comment by dromazmj** [comment]
Im implementing this resource now

**Comment by clintoncwolfe** [comment]
Refs #209 and #210

**Comment by clintoncwolfe** [comment]
In place, #209 and #228
