### ISSUE TITLE
Enhancement for aws_iam_root_user

### ISSUE THREAD

**Issue by rx294** [chef/inspec-aws#176]
Please consider the following features to support cis-aws-foundations-1.14
Enhancements:
check if MFA is virtual for root user

```
  describe aws_iam_root_user do
    its('virtual_mfa?') { should be false }
  end
```

Code suggestion:

```
  def virtual_mfa?
    !@client.list_virtual_mfa_devices.virtual_mfa_devices.empty?
  end
```

**Comment by chris-redekop** [comment]
I think @Stiffni has a PR for something similar over in #124 .  Would that change address this issue?

**Comment by rx294** [comment]
Ok thats good enough...hope the PR will be merged soon...Thank you @chris-redekop
