### ISSUE TITLE
EC2 Instance - Tags are cumbersome to assert

### ISSUE THREAD

**Issue by burtlo** [chef/inspec-aws#225]
The current system to verify the tags for an `aws_ec2_instance` feels cumbersome and not similar to way you use a lot of other InSpec.

```ruby
describe aws_ec2_instance('i-0d46cd56fa5bda893') do
  its(:tags) { should include({ :key => 'Name', :value => 'jhnftz-inspec-lab-exam-env' }) }
end
```

I would propose the following:

```ruby
describe aws_ec2_instance('i-0d46cd56fa5bda893') do
  its(:tags) { should include(Name: 'jhnftz-inspec-lab-exam-env') }
  # ... OR ...
  its(:tags) { should have_tag(Name: 'jhnftz-inspec-lab-exam-env') }
  # ... OR ...
  it { should have_tag(Name: 'jhnftz-inspec-lab-exam-env') }
end
```

A rough implementation that supports all three of these can be found here: https://github.com/burtlo/inspec-aws/commit/0a7aaa5e3c835555853087522e1ee2516cab280b

I didn't build tests, name things sanely, or submit a PR because I don't yet know what are the plans for this resource pack in the face of being included into Inspec for the 2.0 release.

**Comment by burtlo** [comment]
OR 

```ruby
describe aws_ec2_instance('i-0d46cd56fa5bda893').tags do
  its(:Name) { should eq 'jhnftz-inspec-lab-exam-env' }
end
```

**Comment by lnxchk** [comment]
I was thinking about this too while working on a talk. In some instances, I'd just like to know that a tag exists on the object and has some value, not necessarily that it has a specific value. 

For example, if I'm looking at any running instance in a team account, I might want to know that it has the 'Contact' tag, but that value might be any of N different values. Could I check that? Or is it too vague for what InSpec wants to accomplish?

**Comment by burtlo** [comment]
@lnxchk that's important for some of the organizations here at Chef that set up those reaper scripts based on a particular tag. And right now that would be supported through the following:

```
describe aws_ec2_instance('i-0d46cd56fa5bda893') do
  its('tags.keys') { should include('Contact') }
end
```

**Comment by lnxchk** [comment]
@burtlo oh. I couldn't get that to work. 
     ×  EC2 Instance i-01bc3ca909b7e67f3 tags.keys 
     undefined method `keys' for #<Array:0x007ff9056a14d0>

Is that a recent feature? I'm using the 1.45.13 version of inspec in chefdk.

**Comment by clintoncwolfe** [comment]
Over in inspec-azure, tags are handled by generating method names:

```
# ( from an integration test)
 it { should have_tags }
 its('tag_count') { should be 1 }
 its('tags') { should include 'CreatedBy' }
 its('CreatedBy_tag') { should cmp 'Inspec Azure Integration Tests' }
```

`tags.CreatedBy { should cmp 'Inspec Azure Integration Tests' }` would read more 'inspec-ish' to me.

As inspec-aws is still in incubator mode, we can change the interface.  If we're uncertain, I'd recommend withdrawing the tags facility for now during the merge to core, so we can create something we're happy with.  

No other resource currently offers tag facilities, and I think anything we introduce should be consistent across taggable resources.
