### ISSUE TITLE
EC2 Instance - security_groups should return an AwsEc2SecurityGroups collection

### ISSUE THREAD

**Issue by burtlo** [chef/inspec-aws#226]
Currently if I want to verify a security group for an `aws_ec2_instance` it can be done with the following:

```ruby
describe aws_ec2_instance('i-0d46cd56fa5bda893') do
  its(:security_groups) { should include({ id: 'sg-b88c6dcf', name: 'launch-wizard-106' }) }
  its(:security_groups) { should include(id: 'sg-b88c6dcf', name: 'launch-wizard-106') }
  # Good if there is only one security group. I believe security groups can have multiple
  its(:security_groups) { should cmp({ id: 'sg-b88c6dcf', name: 'launch-wizard-106' }) }
  its(:security_groups) { should cmp( id: 'sg-b88c6dcf', name: 'launch-wizard-106' ) }
end
```

I think that it would be a better experience if the `AWSEc2Instance` return an `AwsEc2SecurityGroups` collection.

```ruby
describe aws_ec2_instance('i-0d46cd56fa5bda893') do
  # @note this fails because the `aws_security_group` resources/helper_method is not defined in this scope.
  its(:security_groups) { should include(aws_security_group('sg-b88c6dcf')) }
  # Perhaps this ...
  its(:security_groups) { should has_group(id: 'sg-b88c6dcf') }
  its(:security_groups) { should has_group(name: 'launch-wizard-106') }
end
```

**Comment by clintoncwolfe** [comment]
I agree that the security_groups property is a bit awkward, being an array of hashes (what I term "raw" values).  But moving in the direction of providing "cooked" values - InSpec resources - is actually pretty problematic, especially in the output phase of the test.  While InSpec core resources are by no means consistent on this, on new resources we've taken the stance that properties should be as simple as possible.  So, here, I'd suggest removing the `security_groups` property entirely, and replacing with two simple array-of-strings properties:

```
describe aws_ec2_instance('i-...') do
  its(:security_group_ids) { should include 'sg-12345678' }
  its(:security_group_names) { should include 'launch-wizard-123' }
end
```

If someone does want to get access to the InSpec resource related to the ec2 instance, that's fairly straightforward:

```
aws_ec2_instance('i-...').security_group_ids.each do |sg_id|
  describe aws_ec2_security_group(sg_id) do
     # Your tests here
  end
end
```
