### ISSUE TITLE
Ensure AWS Resources are Destroyed for CI Usage

### ISSUE THREAD

**Issue by mtjandra** [chef/inspec-aws#40]
PR #56 .

Currently when you run `bundle exec rake test:integration` AWS resources are not destroyed if the integration tests fail. There should be an option to ensure the cleanup of AWS resources regardless of the results from the integration tests. 

For example you might run `bundle exec rake test:integration --force-cleanup`

**Comment by chris-redekop** [comment]
Fixed by #56.
