### ISSUE TITLE
Fix Terraform Env Name

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#52]
PR #57 .

Instead of generating a random environment identifier during the setup of our integration tests, use a fixed one based on an input.  (Consider defaulting the environment identifier to the hostname, or not defaulting it.)

The idea is that it should be possible to imbue these IDs with human-level meaning, so we can link a Terraform environment identifier--which appears in the AWS console--to a person or a task.

**Comment by mtjandra** [comment]
@chris-redekop You can set an environment variable before executing your tests. From the README `If you want to use a specific terraform environment, set environment variable INSPEC_TERRAFORM_ENV`. Does this not apply to your case?

**Comment by chris-redekop** [comment]
I think a better title for this issue might be, "Don't default the Terraform env ID to a random number."

I think we should take this random-defaulting out, because I find it counter productive.  When I see a long-running EC2 instance prefixed with F27s3wi7 (or similar) it doesn't help me identify the human behind the instance.  I want to be able to tie a test resource back to a person so I can work with them to properly manage the long-running resources.

What do you think?
