### ISSUE TITLE
configure_test_environment should fail if env exists

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#53]
Currently, the **configure_test_environment** creates a new environment on each run, regardless if one has already been created (and has running resources).  This "hides" the old environment, making it more difficult to track/manage.

Before creating a new Terraform **env**, check to see if the previous one exists and fail if it does.  (This might be hard to do until #52 and might have to wait for that fix.)

**Comment by chris-redekop** [comment]
Just need a quick test on this one--we expect this to exhibit the desired behaviour once the fixes to #40 and #52 are in.

**Comment by mtjandra** [comment]
I don't think the PRs referenced will fully satisfy your needs. It will fail if you try and create an environment with the same name, but it will not warn you of a previously existing one before prompting for a new environment, or using the one defined in your environment variable. It sounds like you want to warn if any previous environment exists.
