### ISSUE TITLE
Ask AWS re: API access to console-password-last-used-date

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#55]
As discussed in #38, we can only get access-key-last-used-date currently, which blocks our completion of Milestone 1.

**Comment by chris-redekop** [comment]
I did raise a support issue on this.  An internal feature request has been raised at AWS but there is no ETA.

@mtjandra , @Rugbyte , @aduric , @vix633 , any questions/comments/concerns before I close?

**Comment by vix633** [comment]
LGTM

**Comment by mtjandra** [comment]
Sounds good to me. Although you may want to keep this or a separate issue open. That way if AWS ever adds support, some future person can implement.
