### ISSUE TITLE
Milestone #1 demo - Recommendations 1.5-1.11

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#65]
We want to create an InSpec profile that clearly demonstrates each of the recommendations.  When run against an account, the profile should fail if the account does not follow the recommendations.

Start with the password policy, which should all be in master and ready to go.

If 1.5-1.11 are not yet demoable, then create follow-up issues.

**Comment by clintoncwolfe** [comment]
I'm closing this for now.  on this prject, we're mainly concerned with the creation of AWS inspec resources, and not directly with the use to which those resources are put - such as creating a CIS profile.
