### ISSUE TITLE
[SPIKE] Plan remaining work for Milestone #1

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#67]
Some recommendations don't make sense in a pass/fail environment, while others are not (practically) implementable with the AWS API.  Which recommendations won't we implement?

**Comment by chris-redekop** [comment]
@Rugbyte and I went through the CIS-benchmarke IAM recommendations, and created all remaining issues.  Simon, would you please attach your tracking spreadsheet to this issue?

**Comment by Rugbyte** [comment]
[CIS Benchmark.xlsx](https://github.com/chef/inspec-aws/files/1162738/CIS.Benchmark.xlsx)
Here is the spreadsheet for what we are doing for the milestone

**Comment by chris-redekop** [comment]
Thanks, @Rugbyte .  @Stiffni and @aduric , would you please review the attached spreadsheet and the resulting issues in our backlog?  Looking to get a shared understanding of the remaining work.

**Comment by aduric** [comment]
@chris-redekop Seems to accurately reflect the backlog. I couldn't find any glaring omissions.

**Comment by Stiffni** [comment]
Hey @chris-redekop 
This seems good to me too! I think the ones we are omitting make sense, and the backlog seems to line up with what we are committing to complete.

**Comment by chris-redekop** [comment]
Closing based on positive feedback.
