### ISSUE TITLE
Add support for using AWS credentials from an instance's role

### ISSUE THREAD

**Issue by scarolan** [chef/inspec-aws#68]
I think this should be fairly simple to implement.  (Famous last words...)

Fetch the temporary access key and secret key from the metadata API endpoint.
Store those keys and use them when making calls to AWS.  This might help

http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html

**Comment by clintoncwolfe** [comment]
I'm not totally clear on what's being requested here - are you wanting to audit AWS IAM roles, or are you wanting to run inspec (with inspec-aws resource pack) on an instance with a role, and use the instance role to get temporary credentials?  

I think it's likely the latter, but just want to check.  We can use session tokens now (#107)

**Comment by aaronlippold** [comment]
This will be a  primary capability in use for the AWS / GovCloud use case for one of our government customers. We are having to use a work around now so support for this would be very welcome. @scarolan let me know how we can help.

**Comment by aaronlippold** [comment]
@scarolan @clintoncwolfe would this be the basic order we would be looking for in the _aws_connection.rb?
```
if 
   AssumeRoleCredentials
else if
  Aws::InstanceProfileCredentials
else if  
  SharedCredentials
else
  Credentials
```

**Comment by aaronlippold** [comment]
Do we need to add the code that Roni made for the old process to allow for instance roll credentials? It looks like this code has the same problem the old connector did

**Comment by rx294** [comment]
Looks like the new train implantation allows AWS SDK to pull creds out of the ec2 instance's role...
So it looks like no further action is needed once the train 🚂   takes over 😄
