### ISSUE TITLE
[SPIKE] Consider a "IamPolicyEntities" resource

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#76]
... to look for groups, roles, and users that have a policy.  For recommendation 1.22.

Is the resource too abstract?  What are the alternatives?

```
describe PolicyEntities.where(policy_name="AWSSupport") do
  it {should exist}
end
```

**Comment by Rugbyte** [comment]
So there is a way of proceeding with this request by using something like the sudo code below to find out if it is attached:
IAM::Client.list_policies(only_attached:true) and PolicyName = AWSSupportAccess 

Here is the aws cli call for the above:
```aws iam list-policies --only-attached --query "Policies[?PolicyName=='AWSSupportAccess']"```

**NOTE**
Using the following sudo while testing with the aws cli has provided a false negative:
IAM::Client.list_policies(only_attached:false) and PolicyName = AWSSupportAccess 

Here is the aws cli call for the above:
```aws iam list-policies --no-only-attached --query "Policies[?PolicyName=='AWSSupportAccess']"```

**Comment by clintoncwolfe** [comment]
I really appreciate the good ideas here - avoid duplicating code by having a generic resource.  However, I don't think this is something which control authors would have to know about.  It's an abstraction on our end - "a thing that a policy can apply to".  

I think this would be a property or set of predicates on Users, Roles, and Groups.  Internally, we might abstract that (so that Users, Groups, and Roles can mix-in that functionality without duplication).

```
# pseudocode

# We could do it as an list property
describe aws_iam_user('bob') do
  its('profiles') { should include 'FabulousProfile' }
end

# Or a predicate
describe aws_iam_group('ops-people') do
  it { should have_profile('FabulousProfile') }
end

# (or both)
```

We'd also need to decide: do we always search directly and indirectly attached profiles? Do we provide properties / predicates that make a distinction?
```
# Includes profiles directly attached as well as group 
describe aws_iam_user('bob') do
  its('profiles') { ... }
end

# Only check directly attached profiles
describe aws_iam_user('bob') do
  its('directly_attached_profiles') { ... }
end
```

**Comment by chris-redekop** [comment]
Thanks for the feedback, Clinton.  You went straight to the crux of the matter: which UX is better?  I wasn't sure if control authors--who i assume are well-versed in their target platforms--would more appreciate the compactness of a common type or the clarity/one-to-one mapping of separate resources.

Reading your reply, I'm sold on separate resources with some other way to share code.

What this doesn't cover is the search/filter table aspect.  We don't just need to assert that a particular user/group/role has the policy; we need to assert that *any* user/group/role has the policy.  So something like the following?

```
describe aws_iam_users.where(is_assigned_policy: 'FabulousPolicy') do
  it { should exist }
end

describe aws_iam_groups.where...
```

**Comment by clintoncwolfe** [comment]
Thanks for thinking about this, and for your openness to alternate solutions.  As you can tell, we're doing a push towards UX clarity and keeping the barrier of entry low.

I think your example is perfect.  Given a requirement to ensure that a policy is not in use, I notice that CIS generally says "by any user or group" - so a straightforward approach would be to check the users, then check the groups.

If we do want to say "this policy should not be attached to anyone or anything," we could make a aws_iam_policy (or aws_iam_policies) resource, and try to get an attachment count.  (Which for all I know, may have been the original intent of this!) :)

Thanks again for all your thoughts on the matter!

**Comment by chris-redekop** [comment]
Thanks for the discussion, @clintoncwolfe .  Based on your feedback, I think the following would be a good approach for 1.22

```
describe policy('AwsSupportAccess') do
  it { should exist }
end

describe.one do
  describe policy('AwsSupportAccess') do
   its('user_attachment_count') { should be > 0 }
  end
  describe policy('AwsSupportAccess') do
   its('group_attachment_count') { should be > 0 }
  end
  describe policy('AwsSupportAccess') do
   its('role_attachment_count') { should be > 0 }
  end
end
```

This will require a new policy resource, with five properties:
* name
* exists?
* user_attachment_count
* group_attachment_count
* role_attachment_count

How does this sound?  @Rugbyte and I will just be getting started on this today--let us know if you'd like us to make a course correction!

**Comment by clintoncwolfe** [comment]
aws_iam_policy is provided by #179
