### ISSUE TITLE
[SPIKE] Figure out Role/Policy resources for Recommendation 1.18

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#78]
We need to assert that a role allows and denies specific actions, and that a user/group is not assigned both of two groups.  See the CIS recommendation for more info.

**Comment by Stiffni** [comment]
We looked over the CIS Foundations Benchmark for 1.18, just want to clarify that this recommendation wants us to verify that a user or group is not assigned to both master and manager roles, they can be one or the other. Is that correct? (As well as verifying the role actions?)

**Comment by chris-redekop** [comment]
From the audit section of the recommendation, I took a few tests:

> The output should contain entries with “RoleName”: “<iam_manager_role_name>” and
“Rolename”: “<iam_master_role_name>”

This one is just checking that the roles exist:
```
describe aws_iam_role('master') do
  it { should exist }
end
```

> The <iam_master_role_name> role should include the following Actions with an Allow
effect

This one is trickier, in the general case: we'd need to understand merging policies, checking unnamed policies on a role, permission wildcards, and permission conditions.  The more I think about this, the more I think we'd end up writing AWS's policy simulator.  I propose we do NOT tackle this as part of this story.  In general, @clintoncwolfe , do you have any recommendations or guidelines for InSpec resources interpreting and reasoning about policies.  My concern is the risk of misinterpreting them.

On the subject of which users are assigned both roles, I don't think this applies.  Unlike groups, roles are assumed temporarily--think BMX!--and so we don't need to assert them.  I'm not sure that's clear: who has what roles is less about configuration and more about transient state, so I think it's less important for assertions.

In the end, then, I think this one is just about asserting that a named role exists.  What do you think?

**Comment by clintoncwolfe** [comment]
Hmmm.  In the middle of page 50 of the CIS AWS Benchmark v.1.10, there is also the sentence "No user or group should be able to assume both roles." .  So, I think we'd need to do at least three things, in order of "fruit height":

1.  Ensure IAM roles Master and Manager exist (no examination of policies; names might be parameterized)
2.  Ensure no user can assume both roles ( that is, no users have AssumeRole permission either explicitly for those roles, or for '*')
3.  Verify the policies on the roles.  

My instincts say an MVP might do 1 and 2, but that might be explored further.  For 2, we don't need a full policy parser, we can hardcode that probe into the JSON.

We'll need some kind of smarter policy parser eventually for 3.  We can start off with minimal features - here, we don't need to look at Resource; and we might delay adding the Conditional clause.

**Comment by chris-redekop** [comment]
Thanks for the feedback, Clinton, and clarification of the recommendation.  (Apologies, Steffanie, if that's what you meant!)  On second thought about the parser, I perused the SDK docs and discovererd that AWS's API actually includes access to their policy simulator!

http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#simulate_principal_policy-instance_method

Clinton, I see how we can get the necessary info from the AWS SDK for tasks 1 and 2 above.  I also see how we can craft the InSpec DSL for the first task.  I'm not sure, though, what the DSL should look like for the second task,

> Ensure no user can assume both roles

Do you have an idea yet of what the DSL for task 2 should look like?
 
I don't have much to say about the third task yet, either.  I want to take a closer look at the API docs first.  :smile:

**Comment by clintoncwolfe** [comment]
Well, we could do this.... mind you, this is fairly ruby-ish.

```ruby
control '1.18' do
  describe aws_iam_users.where { |u| u.can_assume_role?('Manager') and u.can_assume_role?('Master') } do
    it { should_not exist }
  end

  describe aws_iam_users.where { |u| u.can_assume_role?('*') } do
    it { should_not exist }
  end
end
```

Using "filter criteria"-style (rather than the more complex block syntax above), we'd have to chain the filters, which is totally possible but @adamleff says it's a UX issue (worse than block syntax?)

```ruby
control '1.18' do
  describe aws_iam_users.where( can_assume_role: 'Manager').where( can_assume_role: 'Master') do
    it { should_not exist }
  end

  describe aws_iam_users.where( can_assume_role: '*') do
    it { should_not exist }
  end
end
```

I personally think the second approach reads better.

This all assumes we implement a `can_assume_role` method.

**Comment by chris-redekop** [comment]
Ah, neat!  I didn't know (or maybe I just didn't recall) that filter methods can take arguments.  🎉

**Comment by chris-redekop** [comment]
I see two clear stories here:
1. Add a role resource with an exists property.
2. Add a can_assume to users' filter-table (assuming, @clintoncwolfe , that we're OK with changing later based on the outcome of #111).

Aside from the third requirement--Verify the policies on the roles.--shall I create issues for these, @clintoncwolfe ?

On the third requirement, I'm still unsure what to do.  I've looked at the API, and I think it can fulfill our requirements.  The crux for me is the InSpec DSL.  We need to make an assertion about the relationship between a few things: the role/user/group, the action, and the target resource.  I'm not sure how we can elegantly combine those three things into an assertion.  @clintoncwolfe , what do you think?

```
describe aws_iam_role('role name') do
  it { should have_permission_to( 's3:PutObject', 'bucket X') } # < how do we support parameters here?
end
```
