### ISSUE TITLE
More resources based on NIST 800-53 controls mapping for AWS

### ISSUE THREAD

**Issue by arlimus** [chef/inspec-aws#88]
Considering resources we should probably have a look at the NIST requirements and see what is needed. 

https://s3.amazonaws.com/quickstart-reference/enterprise-accelerator/nist/latest/assets/NIST-800-53-Security-Controls-Mapping.xlsx

http://docs.aws.amazon.com/quickstart/latest/accelerator-nist/welcome.html

**Comment by arlimus** [comment]
Requested from the gov space 😉

**Comment by aaronlippold** [comment]
👍 This will have *very* wide impact and utilization.
