### ISSUE TITLE
aws_iam_users for Recommendation 1.2

### ISSUE THREAD

**Issue by chris-redekop** [chef/inspec-aws#9]
Now that we have a single **aws_iam_user**, add the ability to query for users with a new **aws_iam_users** resource.

Existing query logic for InSpec's core **user** resource is at 

https://github.com/chef/inspec/blob/master/lib/resources/users.rb#L72-L89 and

https://github.com/chef/inspec/blob/master/lib/resources/users.rb#L103-L105

Example usage:
```ruby
describe aws_iam_users.where(:has_console_password? => true) do
  its('has_mfa_enabled?') { should_not include false }
end
```
user_provider
- [X] create aws_user_provider.rb - https://github.com/chef/inspec-aws/compare/master...Issue9-UserProvider
- [X] make `aws_iam_user` use `aws_user_provider`
- [X] fix `aws_iam_user` unit tests
- [x] add `aws_user_provider` unit tests
- [x] merge changes above

get_users
- [x] add `get_users` to `aws_user_provider `(and unit tests)
- [x] investigate potential paging of users by aws
- [x] run manual integration test
- [x] merge changes above

aws_am_users
- [x] add aws_iam_users.rb which will call `get_users` to populate the filter table
- [x] `aws_iam_users` unit tests
- [x] `aws_iam_users` integration tests

**Comment by Stiffni** [comment]
The branch Alex and I worked on last week is [aws-iam-users-bro](https://github.com/chef/inspec-aws/compare/master...aws-iam-users-bro), where we added aws_iam_users.rb and updated the constructor/initializer for aws_iam_user so it can take a user or a name.

**Comment by Stiffni** [comment]
@aduric and I started working on the [unit tests for aws_iam_users](https://github.com/chef/inspec-aws/commit/beb2bba6e8b7330bb9ac59933f10487d287dac2d) today. There still needs to be more unit tests added, and the integration tests are still up for grabs!

**Comment by Rugbyte** [comment]
Fixed the control test files in order to get the integration tests to run properly

**Comment by Rugbyte** [comment]
This is currently awaiting merge of PR #71 before closing
