### ISSUE TITLE
RFC:`aws_s3bucket` and `aws_s3buckets` resources for vpc and or iam_groups??

### ISSUE THREAD

**Issue by aaronlippold** [chef/inspec-aws#91]
Examples of Questions of Concerns: 

i.e. ensure users didn't open an S3 bucket to the world
i.e. ensure that s3 only open to particular users
i.e. ensure that only a particular service, port, and or IAM
i.e. ensure that I can pass a list of IAMs to the resource and that it can validate that the S3 bucket has or has_not access.
i.e. ensure the S3 bucket is only accessible form https, or a known uri etc.
i.e. ensure that the S3 bucket has logging enabled, set, reporting to the 'known' location
i.e. ensure that the 'POLICY SETTINGS' for S3 is set or not set

**Comment by chris-rock** [comment]
@aaronlippold that is a great idea. Do you want to recursively test all files? The iam policy is interesting! I think we need to find a good way to write the test. Do you have an automation to create the configuration already?

**Comment by aaronlippold** [comment]
Both would be great, put remember limits for recursion have to be in place. The buckets first, the files second.

**Comment by aaronlippold** [comment]
@clintoncwolfe @chris-rock Is this were we want to push the "question list" for the S3 resource or do we want to start a new RFC?

**Comment by clintoncwolfe** [comment]
Thank you for your thoughts, @aaronlippold . I think this is a fine place for people to discuss their ideas about what they'd like out of s3-related resources.

A lot of the possibilities here are very complex.  I'd like to see a minimum viable aws_s3_bucket and aws_s3_buckets resources (which means docs, unit and integration tests, and a basic implementation that can do search by name).  We can also easily expose a create_date property at this point, since it is revealed in [list_buckets](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_buckets-instance_method).

Beyond that, I'd want (generally) to have a separate PR for each new use case.  The AWS SDK here is very fine-grained.  If someone has a use case for a particular property, or search criteria, or a high-level summary matcher (I could imagine `is_world_accessible?`, which could touch a lot of things under the hood), we can evaluate and iterate on the addition on its own track, basing off the simple MVP resources.

We may eventually find we need additional resources, or need to rely on interactions with others (such as the iam_policy resources being considered).

**Comment by aaronlippold** [comment]
@clintoncwolfe I agree we should create a use_case for each interaction but I think that our first use case is the one in the news - the 'publicly accessible' use case. In our research we found that 'public' had three data points to it - which are listed here: 

- http://docs.aws.amazon.com/AmazonS3/latest/user-guide/bucket-permissions-check.html,

and I think if we cover the general functions that make these three validations work we will actually cover a lot of the larger use cases.

Secondly - at least for me - understanding and defining what 'general properties' - i.e. what `params` will look like - will be initially populated is key. I would guess that your previous work with the other resources helps inform the general pattern. Can you provide any thoughts, insight or lessons-learned on this? 

As an example, I started a rough and ugly cli-driven example of the public accessibility check - I have to round out the two other sub-checks to round it out.

```
control "s3bucket" do
  impact 0.7
  title "Ensure there are no Publicly Accessable S3 Buckets"
  desc "Ensure that we don't get in the newspaper again ..."

  tag nist: "AC...<tbd>"

  buckets = inspec.command("aws s3api list-buckets --query 'Buckets[].Name' --output text").stdout.strip.lines

  buckets.each do |bucket|
    results = inspec.command("aws s3api get-bucket-acl --bucket #{bucket} --query Grants[?Grantee.Type==\'Group\'].[Grantee.URI,Permission] --output text | awk '{ print $1 }'").stdout.strip
     describe results do
       it { should_not include "AllUsers" }
       it { should_not include "AuthenticatedUsers" }
     end
   end
end
```

**Comment by clintoncwolfe** [comment]
As I mentioned, I'd like to see a simple base first.  That means the ability to search for a bucket by name, and that's about it.  Along with that comes the docs, unit tests, and integration tests.  That's easy to write, easy to evaluate, and easy to accept.

My experience with other resources has shown me that the initial properties of the first draft of a resource is largely determined by the AWS API.  In this case, we'd be relying on [list_buckets](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_buckets-instance_method), which returns a `bucket_name` and `create_date` - that's it.

As people with particular needs - like your desire to ensure no public access - they would then make pull requests once the base has been established.  Implementation details on such complex features are likely to be more contentious, and I'd like to be able to isolate that discussion and development from other lines of work, so they can iterate independently.  Does that make sense?

**Comment by clintoncwolfe** [comment]
For your example, I might imagine something like this:

```
describe aws_s3_buckets.where { is_publically_accessible } do
  it { should_not exist }
end
```

And we'd be doing some heavy lifting in the is_publically_accessible filter implementation.  We wouldn't want to expose those guts to the control author (though maybe we would also offer policy querying abilities, at some point).  Our team's goal is to focus on readablity.

**Comment by aaronlippold** [comment]
@clintoncwolfe totally agree and your example is exactly what we would like to see, now the failure on that would be interesting given that we have considerations of both ACLS and policy data to return and possible reasons for failure. Yes though the above example is close to what I am thinking of as an end state.

**Comment by aaronlippold** [comment]
I think I may have to refine my comment from Nov 2nd, I think we have to consider objects inside a bucket as an equal citizen as the bucket itself.
